### ISSUE TITLE
Basic Improvements

### ISSUE THREAD

**Issue by afzalali15** [ahmad-dev7/Flash_Chat#1]
1. Chat thread should show date time
2. While registering accept Name field from user, show the same name inside chat (showing email is not good)
3. Don't show previous chat to newly joined user (optional)
4. In place of Logout button on chat page, show profile icon and navigate to new page
    a. User can see his profile details
    b. Logout option in bottom
    c. Show app version

**Comment by ahmad-dev7** [comment]
Thank you for raising the issue, I'll surely work on it.
